### ISSUE TITLE
Error generating PDF reports

### ISSUE THREAD

**Issue by jamiefuller96** [gurock/testrail-docker#1]
The public available image at hub.docker.com/testrail/apache:latest has some additional config that isn't present in the testrail-apache dockerFile in this repo.

When building the image from the dockerFile, the task.php fails to generate PDF reports with this error:

`
/var/www/testrail/app/helpers/../../bin/phantomjs_x86_64: error while loading shared libraries: libfontconfig.so.1: cannot open shared object file: No such file or directory
`

This is fixed by adding the below to the dockerFile:

`ENV OPENSSL_CONF="/etc/ssl/"`

and installing libfontconfig1

`RUN \
    apt-get update && \
    apt-get install -y --no-install-recommends curl zip unzip wget iputils-ping mariadb-client && \
    apt-get install -y --no-install-recommends zlib1g-dev libcurl4-gnutls-dev libldap2-dev zlib1g-dev libxml2-dev libfontconfig1 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*`

It then works as expected.

Both changes are already in the prebuilt image on dockerhub:

https://hub.docker.com/layers/testrail/apache/latest/images/sha256-58c49e6ed5ce94d15f2f351ca0e8794ff37cf7031647a8ad167836b60d0a0dfe

**Comment by cbreit** [comment]
Thx for the hint.
Is fixed.
--> See [1](https://github.com/gurock/testrail-docker/blob/d6ca99b73308b4f6cf24e7c0c590289aa4111b91/Dockerfiles/testrail_apache/Dockerfile#L14) and [2](https://github.com/gurock/testrail-docker/blob/d6ca99b73308b4f6cf24e7c0c590289aa4111b91/Dockerfiles/testrail_apache/Dockerfile#L25)
