### ISSUE TITLE
Reports fail to load when 

### ISSUE THREAD

**Issue by beeritis** [gurock/testrail-docker#50]
Since upgrading to version v8.0.1 (Default 1029) , when we try and view reports , they no longer load. 

This was fine in version 7.5.3.

If we try and view a report - example url  : https://mydomain.example/index.php?/reports/view/1 .

The wheel of death keeps on spinning. 

I loaded up dev tools to try and debug this and we get the following error 

```
Refused to frame 'https://mydomain.example/index.php?/reports/render/1' because it violates the following Content Security Policy directive: "frame-src https://app.pendo.io https://*.testrail-staging.com https://*.testrail.com https://*.testrail.io http://*.eu-central-1.compute.amazonaws.com https://*.testrail.net".
```

This looks like a piece of code that possibly isn't meant to be there ?

Looks to be cause by this piece in the header within  `index.php` . 

In the process of trying to manually remove this to see if it fixes the issue, although needs a proper solution. 
Our domain does not fall into these unsafe ones below . Happy to try an alternative fix if there is one but appears to be a bug as it was working in previous versions.

```
<meta http-equiv="Content-Security-Policy" content="script-src 'self' 'unsafe-inline' 'unsafe-eval' https://static.testrail-staging.com https://static.testrail.com https://static.testrail.io https://cdn.pendo.io https://data.pendo.io https://app.pendo.io https://pendo-static-5699730914541568.storage.googleapis.com https://cdn.embedly.com ; style-src 'self' 'unsafe-inline' https://static.testrail-staging.com https://static.testrail.com https://static.testrail.io https://pendo-static-5699730914541568.storage.googleapis.com ; style-src-elem 'self' 'unsafe-inline' https://static.testrail-staging.com https://static.testrail.com https://static.testrail.io https://pendo-static-5699730914541568.storage.googleapis.com ; style-src-attr 'self' 'unsafe-inline'  ; font-src 'self' https://fonts.gstatic.com https://static.testrail-staging.com https://static.testrail.com https://static.testrail.io ; connect-src 'self' https://app.pendo.io https://data.pendo.io https://pendo-static-5699730914541568.storage.googleapis.com ; media-src *  ; object-src 'none'  ; prefetch-src 'self'  ; worker-src 'none'  ; base-uri 'self'  ; frame-src  https://app.pendo.io https://*.testrail-staging.com https://*.testrail.com https://*.testrail.io http://*.eu-central-1.compute.amazonaws.com https://*.testrail.net ; child-src  https://app.pendo.io ;">
```

Thanks,

**Comment by beeritis** [comment]
Now resolved - didn't spot the "CSP - Allow access TestRail to remote addresses" setting in security .

**Comment by test2387** [comment]
Hi @beeritis, Could you please share how did you resolve this issue? We are getting the same error, any pointers is appreciated. Thanks

**Comment by beeritis** [comment]
Hi @test2387 ,

I did this as follows:

Go into Administration -> Under site settings go to "Manage site settings" -> Security.

Within the security settings, at the bottom of the page there is a setting called "CSP - Allow access TestRail to remote addresses" , make sure that checkbox is ticked.

then in the text box below put in your testrail url e.g. https://mytestrail.com . 

Then "Save Settings" . 

That's what worked for me at least . Hope that helps.

**Comment by test2387** [comment]
Thank you @beeritis, That did the trick.

**Comment by Mik4sa** [comment]
You can also add `'self'`. So the actual url is not interesting then.
